esphome:
  name: home_automation
  platform: ESP32
  board: upesy_wroom

wifi:
  ssid: "Siddhartrockx"
  password: "$iddhart@Wif@0152"

logger:
api:


# Relays Configuration
switch:
  - platform: gpio
    pin: 23
    name: "Relay 1"
    id: relay_1

  - platform: gpio
    pin: 22
    name: "Relay 2"
    id: relay_2

  - platform: gpio
    pin: 21
    name: "Relay 3"
    id: relay_3

  - platform: gpio
    pin: 19
    name: "Relay 4"
    id: relay_4

  - platform: gpio
    pin:
      number: 15
      mode: OUTPUT
      inverted: true  # Ensures the buzzer is silent when GPIO is LOW
    name: "Buzzer"
    id: buzzer
    on_turn_on:
      - while:
          condition:
            switch.is_on: buzzer  # Loop while the buzzer is ON
          then:
            - switch.turn_on: buzzer
            - delay: 1s  # Buzzer ON for 1 second
            - switch.turn_off: buzzer
            - delay: 1s  # Delay for 1 second before turning the buzzer on again
# Toggle Switches for Manual Control
binary_sensor:
  - platform: gpio
    pin:
      number: 18
      mode: INPUT_PULLUP
    name: "Switch 1"
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_1
            then:
              - switch.turn_on: relay_1
            else:
              - switch.turn_off: relay_1
    id: switch_1

  - platform: gpio
    pin:
      number: 25
      mode: INPUT_PULLUP
    name: "Switch 2"
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_2
            then:
              - switch.turn_on: relay_2
            else:
              - switch.turn_off: relay_2
    id: switch_2

  - platform: gpio
    pin:
      number: 17
      mode: INPUT_PULLUP
    name: "Switch 3"
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_3
            then:
              - switch.turn_on: relay_3
            else:
              - switch.turn_off: relay_3
    id: switch_3

  - platform: gpio
    pin:
      number: 16
      mode: INPUT_PULLUP
    name: "Switch 4"
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_4
            then:
              - switch.turn_on: relay_4
            else:
              - switch.turn_off: relay_4
    id: switch_4

# PIR Motion Sensor
  - platform: gpio
    pin: 13
    name: "Motion Sensor"
    device_class: motion
    filters:
      - delayed_on: 500ms

# DHT11 Temperature and Humidity Sensor
sensor:
  - platform: dht
    pin: 4
    temperature:
      name: "Room Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
    humidity:
      name: "Room Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 1
    update_interval: 10s
    model: DHT11
