esphome:
  name: homeautomation
  platform: ESP32
  board: upesy_wroom


wifi:
  ssid: "Siddhartrockx"
  password: "$iddhart@Wif@0152"


captive_portal:

logger:

api:



# Relays Configuration
switch:
  - platform: gpio
    pin:
      number: 23
      inverted: true  # Inverted for proper relay behavior
    name: "Relay 1"
    id: relay_1

  - platform: gpio
    pin:
      number: 22
      inverted: true
    name: "Relay 2"
    id: relay_2

  - platform: gpio
    pin:
      number: 21
      inverted: true
    name: "Relay 3"
    id: relay_3

  - platform: gpio
    pin:
      number: 19
      inverted: true
    name: "Relay 4"
    id: relay_4

  - platform: gpio
    pin:
      number: 15
      mode: OUTPUT
      inverted: true  # Ensures the buzzer is silent when GPIO is LOW
    name: "Buzzer"
    id: buzzer


# Toggle Switches for Manual Control
binary_sensor:
  - platform: gpio
    pin:
      number: 18
      inverted: true
      mode: INPUT_PULLUP
    name: "Switch 1"
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_1
            then:
              - switch.turn_on: relay_1
            else:
              - switch.turn_off: relay_1
    id: switch_1

  - platform: gpio
    pin:
      number: 25
      inverted: true
      mode: INPUT_PULLUP
    name: "Switch 2"
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_2
            then:
              - switch.turn_on: relay_2
            else:
              - switch.turn_off: relay_2
    id: switch_2

  - platform: gpio
    pin:
      number: 17
      inverted: true
      mode: INPUT_PULLUP
    name: "Switch 3"
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_3
            then:
              - switch.turn_on: relay_3
            else:
              - switch.turn_off: relay_3
    id: switch_3

  - platform: gpio
    pin:
      number: 16
      inverted: true
      mode: INPUT_PULLUP
    name: "Switch 4"
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: switch_4
            then:
              - switch.turn_on: relay_4
            else:
              - switch.turn_off: relay_4
    id: switch_4

# PIR Motion Sensor
  - platform: gpio
    pin: 4
    name: "Motion Sensor"
    device_class: motion
    filters:
      - delayed_on: 500ms

# DHT11 Temperature and Humidity Sensor
sensor:
  - platform: dht
    pin: 13
    temperature:
      name: "Room Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
    humidity:
      name: "Room Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 1
    update_interval: 30s
    model: DHT11
